# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""add bootstrap_run.run_steps

Revision ID: 130e97b1c430
Revises: 5020da27ed4b
Create Date: 2026-09-07 09:58:00.000000

Hand-written, matching ``5020da27ed4b``'s own note: autogenerate proposes a wrong
diff against this table (no ``schema_translate_map`` during autogenerate,
``include_schemas`` off), so treat any autogenerated OM diff as a bug.

Resolves the schema token to its *real* name (:func:`om_schema`) rather than
passing ``OM_SCHEMA_SYMBOL`` straight to ``op.add_column``, unlike
``5020da27ed4b``'s ``op.create_table``: ``ADD COLUMN`` does not get the same
runtime ``schema_translate_map`` rewrite ``CREATE TABLE`` does (verified against
a real SQLite run -- the symbol reaches the driver untranslated and SQLite
raises "no such table: om_schema.bootstrap_run"), so this migration resolves it
itself instead of relying on that translation happening.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.sep.apps.shared.om.config import om_schema
from app.sep.config import sep_settings


# revision identifiers, used by Alembic.
revision: str = "130e97b1c430"
down_revision: Union[str, None] = "5020da27ed4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "bootstrap_run",
        sa.Column(
            "run_steps",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
            server_default="[]",
        ),
        schema=om_schema(sep_settings.DATABASE),
    )


def downgrade() -> None:
    op.drop_column(
        "bootstrap_run", "run_steps", schema=om_schema(sep_settings.DATABASE)
    )
