# Copyright (C) 2026 Percona LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""create the bootstrap_run table

Revision ID: 5020da27ed4b
Revises:
Create Date: 2026-09-07 07:48:14.858060

``om_bootstrap`` is a separate app from ``om_inventory``, and each app's
migrations are an independent branch with no ordering between them
(``om_inventory``'s own ``a3f1c8d24b71`` makes the same point) -- so this
revision creates OM's shared schema defensively too, rather than assuming
``om_inventory``'s migration already ran first.

The schema is named symbolically throughout -- ``schema="om_schema"``,
translated by the connection (``app/sep/migrations/env.py``) -- with the single
exception of ``CREATE SCHEMA``, which is raw DDL and therefore untranslated.

Hand-written, and it has to stay that way: Alembic applies no
``schema_translate_map`` during autogenerate and ``include_schemas`` is off, so
``--autogenerate`` proposes creating a literal ``om_schema`` and re-creating this
table on every run. Treat an autogenerated OM diff as a bug.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.sep.apps.shared.om.config import OM_SCHEMA_SYMBOL, om_schema
from app.sep.config import sep_settings


# revision identifiers, used by Alembic.
revision: str = "5020da27ed4b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("om_bootstrap",)
depends_on: Union[str, Sequence[str], None] = None


def _create_schema_if_needed() -> str | None:
    """Create OM's schema on a bind that has one, and report what it is called.

    :return: The real schema name, or ``None`` when the bind has no schemas and
        this table therefore lives in the default one.
    """
    schema = om_schema(sep_settings.DATABASE)
    if schema is not None:
        op.execute(sa.schema.CreateSchema(schema, if_not_exists=True))
    return schema


def upgrade() -> None:
    schema = _create_schema_if_needed()

    # Inspect the schema the table actually lands in, asking for the *real* name --
    # the token is not a schema anything can be inspected in.
    existing = set(sa.inspect(op.get_bind()).get_table_names(schema=schema))

    if "bootstrap_run" in existing:
        return

    op.create_table(
        "bootstrap_run",
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        # BaseUUIDSQLModel's own columns. Omitting them is the mistake that makes
        # the table exist and every query against it fail.
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            # The enum's member NAMES, not its values -- SQLAlchemy's non-native
            # Enum persists by name, same trap ``ProbeRunStatus``'s own migration
            # documents.
            sa.Enum(
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "ROLLED_BACK",
                name="bootstraprunstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "install_method",
            sa.Enum(
                "PACKAGES",
                "DOCKER",
                "PODMAN",
                name="installmethod",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "os",
            sa.Enum(
                "UBUNTU",
                "ROCKY",
                name="operatingsystem",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("mongodb_version", sa.String(), nullable=False),
        sa.Column("replica_set_name", sa.Text(), nullable=False),
        sa.Column(
            "hosts",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=OM_SCHEMA_SYMBOL,
    )
    op.create_index(
        op.f("ix_bootstrap_run_started_at"),
        "bootstrap_run",
        ["started_at"],
        unique=False,
        schema=OM_SCHEMA_SYMBOL,
    )
    op.create_index(
        op.f("ix_bootstrap_run_status"),
        "bootstrap_run",
        ["status"],
        unique=False,
        schema=OM_SCHEMA_SYMBOL,
    )


def downgrade() -> None:
    # The schema itself is deliberately left behind: it is shared by every OM app,
    # so dropping it here would take another app's tables with it, and each app's
    # migrations are an independent branch with no ordering between them.
    op.drop_index(
        op.f("ix_bootstrap_run_status"),
        table_name="bootstrap_run",
        schema=OM_SCHEMA_SYMBOL,
    )
    op.drop_index(
        op.f("ix_bootstrap_run_started_at"),
        table_name="bootstrap_run",
        schema=OM_SCHEMA_SYMBOL,
    )
    op.drop_table("bootstrap_run", schema=OM_SCHEMA_SYMBOL)
