#!/usr/bin/env bash
# Generate this harness's per-deployment secrets (.env). Idempotent: an existing
# .env is kept, and any slot it predates is appended. PMM owns every remaining
# SEP secret — it writes them into the pmm-sep volume, which the side-car
# reads as files; nothing secret reaches the side-car as environment.
#
# On an arm64 engine it also decides how sep-mysql, the task executor, is
# built: natively from the released multi-arch pmm-client by default, or as the
# amd64 feature-build client under emulation when SEP_MYSQL_PLATFORM=linux/amd64
# is set — which is probed for clone3 first, because that emulation cannot run
# tasks (README.md § Caveats).

set -o nounset
set -o pipefail

if [[ ${DEBUG:-0} == "1" ]]; then
    set -o xtrace
fi

# The released multi-arch client used on arm64; NOMAD_VERSION_FB_TAG, not its
# tools/nomad, ties NOMAD_VERSION to the feature build (README.md "Caveats").
ARM64_CLIENT_IMAGE=docker.io/percona/pmm-client:3.9.1

error() { printf '✗ %s\n' "$*" >&2; }
success() { printf '✓ %s\n' "$*" >&2; }
info() { printf 'ℹ %s\n' "$*" >&2; }
warn() { printf '! %s\n' "$*" >&2; }

# Runs a command with xtrace suspended, restoring it on return (local -).
# DEBUG=1 traces every expansion, and the secrets below reach the wrapped
# commands both as arguments and as sourced assignments — tracing those would
# print every per-deployment secret.
without_xtrace() {
    local -
    set +o xtrace
    "$@"
}

need_cmd() {
    command -v "$1" > /dev/null 2>&1 || {
        error "Missing required command: $1"
        exit 2
    }
}

need_cmd openssl
need_cmd grep

usage() {
    cat << 'EOF'
bootstrap.sh

Generate .env next to this script if it does not exist: the three sep-mysql
passwords and, on an arm64 engine, SEP_MYSQL_PLATFORM plus
SEP_MYSQL_PMM_CLIENT_IMAGE, which decide how the executor is built. An existing
.env is kept and any slot it predates is appended. Run before the first
`docker compose --profile mysql up -d`, after rotating a secret, and after
changing SEP_MYSQL_PLATFORM.

Environment:
  SEP_FB_SKIP_CLONE3_CHECK=1   skip the emulator probe (honoured from .env too)

Options:
  -h, --help    Show this help
EOF
    exit "${1:-0}"
}

[[ $# -eq 0 ]] || case "$1" in
    -h | --help) usage 0 ;;
    *)
        error "Unknown argument: $1"
        usage 2
        ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${script_dir}" || exit 1

ensure_slot() {
    local name="$1" value="$2"
    grep -q "^${name}=" .env && return 0
    {
        # A hand-edited .env may lack the trailing newline the append needs
        [[ -z $(tail -c1 .env) ]] || printf '\n' >> .env
        printf '%s=%s\n' "${name}" "${value}" >> .env
    } || {
        error "Could not write ${name} to .env: MySQL would start without the password this run generated"
        exit 2
    }
    success "Added the ${name} slot to the existing .env"
}

# Replaces a slot's value when the slot exists and appends it otherwise. The
# two executor slots are owned by this script; the passwords never are.
set_slot() {
    local name="$1" value="$2"
    if grep -q "^${name}=" .env; then
        # BSD sed needs a suffix after -i and GNU sed accepts one
        sed -i.bak "s#^${name}=.*#${name}=${value}#" .env && rm -f .env.bak
    else
        [[ -z $(tail -c1 .env) ]] || printf '\n' >> .env
        printf '%s=%s\n' "${name}" "${value}" >> .env
    fi || {
        error "Could not write ${name} to .env: the build would use the slot's stale value"
        exit 2
    }
}

# Wrapped by without_xtrace at the call site: the generated passwords reach
# ensure_slot as arguments
seed_missing_slots() {
    local slot
    for slot in SEP_MYSQL_ROOT_PASSWORD SEP_MYSQL_BACKUP_PASSWORD SEP_MYSQL_PMM_PASSWORD; do
        ensure_slot "${slot}" "$(openssl rand -hex 16)"
    done
}

if [[ -f .env ]]; then
    info "Keeping existing .env"
    chmod 600 .env
    without_xtrace seed_missing_slots
else
    cat > .env << EOF
# Generated by bootstrap.sh — per-deployment feature-build values (gitignored)
# The three passwords are secrets; rotating them after first boot needs the
# sep-mysql-data volume dropped, because the datadir keeps the originals.
# SEP_MYSQL_PLATFORM and SEP_MYSQL_PMM_CLIENT_IMAGE, present on an arm64
# engine, are not secrets: bootstrap.sh manages them (README.md § Caveats).
SEP_MYSQL_ROOT_PASSWORD=$(openssl rand -hex 16)
SEP_MYSQL_BACKUP_PASSWORD=$(openssl rand -hex 16)
SEP_MYSQL_PMM_PASSWORD=$(openssl rand -hex 16)
EOF
    chmod 600 .env
    success "Generated .env"
fi

# Wrapped rather than run at top level: sourcing traces every assignment in
# .env, and ${VAR:?} puts the value itself into the trace line
load_env() {
    # shellcheck disable=SC1091
    source .env
    : "${SEP_MYSQL_ROOT_PASSWORD:?missing in .env}" "${SEP_MYSQL_BACKUP_PASSWORD:?missing in .env}" \
        "${SEP_MYSQL_PMM_PASSWORD:?missing in .env}"
}

# The engine's architecture, not the shell's: a shell under Rosetta reports
# x86_64 on an arm64 engine, and DOCKER_HOST can point anywhere.
engine_arch() {
    local arch=""
    if command -v docker > /dev/null 2>&1; then
        arch="$(docker version --format '{{.Server.Arch}}' 2> /dev/null)"
    fi
    if [[ -z ${arch} ]] && command -v podman > /dev/null 2>&1; then
        arch="$(podman info --format '{{.Host.Arch}}' 2> /dev/null)"
    fi
    [[ -n ${arch} ]] || arch="$(uname -m)"
    case "${arch}" in
        arm64 | aarch64) echo arm64 ;;
        x86_64 | amd64) echo amd64 ;;
        *) echo "${arch}" ;;
    esac
}

# The engine that answers, asked in engine_arch's order, so the probe runs
# against the same engine whose architecture chose the platform. A CLI on PATH
# is not enough: its daemon may be stopped, or DOCKER_HOST may point elsewhere.
container_runtime() {
    if docker version --format '{{.Server.Arch}}' > /dev/null 2>&1; then
        echo docker
        return 0
    fi
    if podman info --format '{{.Host.Arch}}' > /dev/null 2>&1; then
        echo podman
        return 0
    fi
    return 1
}

# Asks the amd64 emulator the question Nomad's executor will ask it: clone3 is
# how raw_exec spawns a task it places into a cgroup via the unified v2
# hierarchy, and QEMU 7.0 and later do not implement it. Only the probe's
# printed verdict decides — a pull or runtime failure says nothing about the
# emulator, so it is reported and does not block.
check_amd64_emulation() {
    [[ ${SEP_FB_SKIP_CLONE3_CHECK:-0} == "1" ]] && return 0
    local runtime out
    runtime="$(container_runtime)" || {
        warn 'no container engine answered: cannot probe the amd64 emulator'
        return 0
    }
    info 'SEP_MYSQL_PLATFORM=linux/amd64 on an arm64 engine: probing the emulator for clone3'
    # On stdin, not a bind mount: the daemon resolves a -v source on its own
    # filesystem, so a remote DOCKER_HOST would mount nothing. Stderr is kept so
    # a failed pull names itself, and the tokens are matched as substrings so
    # that it cannot swallow the verdict.
    out="$("${runtime}" run --rm -i --security-opt seccomp=unconfined --platform linux/amd64 \
        python:3-alpine python3 - < "${script_dir}/../clone3_probe.py" 2>&1)" || true
    case "${out}" in
        *CLONE3_OK*) return 0 ;;
        *CLONE3_ENOSYS*)
            error 'amd64 emulation here has no clone3 (QEMU): sep-mysql would build, register, look healthy, and fail every task'
            error 'Recommended: set SEP_MYSQL_PLATFORM=linux/arm64 in .env and re-run ./bootstrap.sh, so the executor builds natively'
            error 'Alternative, Docker Desktop only: Settings → General → Virtual Machine Manager = "Apple Virtualization framework", then "Use Rosetta for x86_64/amd64 emulation on Apple Silicon", Apply & restart'
            error 'SEP_FB_SKIP_CLONE3_CHECK=1 skips this probe'
            exit 3
            ;;
        *)
            warn "could not probe the amd64 emulator (${out:-no output}); continuing without a verdict"
            return 0
            ;;
    esac
}

# Reads the slots the way compose does, after .env has been sourced: an unset
# or empty SEP_MYSQL_PLATFORM is the amd64 default there, so it is written out
# explicitly here and an arm64 engine gets the native pair unless told not to.
configure_executor_platform() {
    if [[ $(engine_arch) != arm64 ]]; then
        # A .env an arm64 engine wrote would otherwise build the executor arm64
        # here, under the reverse emulation these slots exist to avoid. Absent
        # slots stay absent, so a host that has only ever been amd64 keeps a
        # .env this script never touches.
        if grep -q '^SEP_MYSQL_PLATFORM=' .env; then
            set_slot SEP_MYSQL_PLATFORM linux/amd64
            set_slot SEP_MYSQL_PMM_CLIENT_IMAGE ""
            info 'sep-mysql: amd64 feature-build client (reclaimed the executor slots an arm64 engine had written)'
        fi
        return 0
    fi
    local platform="${SEP_MYSQL_PLATFORM:-linux/arm64}"
    case "${platform}" in
        linux/amd64)
            set_slot SEP_MYSQL_PLATFORM linux/amd64
            # Blank, so compose and the Containerfile fall back to the amd64
            # feature-build client: a released amd64 client would pair another
            # pmm-agent with the feature-build server for no reason.
            set_slot SEP_MYSQL_PMM_CLIENT_IMAGE ""
            info 'sep-mysql: amd64 feature-build client under emulation (SEP_MYSQL_PLATFORM=linux/amd64)'
            check_amd64_emulation
            ;;
        linux/arm64)
            set_slot SEP_MYSQL_PLATFORM linux/arm64
            [[ -n ${SEP_MYSQL_PMM_CLIENT_IMAGE:-} ]] || set_slot SEP_MYSQL_PMM_CLIENT_IMAGE "${ARM64_CLIENT_IMAGE}"
            info "sep-mysql: native arm64 from ${SEP_MYSQL_PMM_CLIENT_IMAGE:-${ARM64_CLIENT_IMAGE}} (the build refuses a NOMAD_VERSION whose feature build is not this PMM_FB_TAG)"
            ;;
        *)
            error "SEP_MYSQL_PLATFORM=${platform}: expected linux/arm64 or linux/amd64"
            exit 2
            ;;
    esac
}

without_xtrace load_env
configure_executor_platform

info "Next: docker compose --profile mysql up -d --build   (or: podman compose ...)"
info "Omit --profile mysql to bring up just pmm-server and sep-sidecar"
