#!/usr/bin/env bash
# Entrypoint for the harness's MySQL target node. Initialises the datadir on
# first boot, creates the credentials the backup payloads authenticate with,
# imports the employees seed, then registers the node and its MySQL service
# with pmm-server and keeps pmm-agent running alongside mysqld — pmm-agent
# supervises the Nomad client, which is what makes this node a selectable
# executor host in SEP.

set -o nounset
set -o pipefail

if [[ ${DEBUG:-0} == "1" ]]; then
    set -o xtrace
fi

error() { printf '✗ %s\n' "$*" >&2; }
success() { printf '✓ %s\n' "$*" >&2; }
info() { printf 'ℹ %s\n' "$*" >&2; }
debug() { [[ ${DEBUG:-0} == "1" ]] && printf '[DEBUG] %s\n' "$*" >&2 || true; }

# Runs a command with xtrace suspended, restoring it on return (local -).
# DEBUG=1 traces every expansion, and the three generated passwords reach the
# commands wrapped below as arguments and as option-file contents — tracing
# those would write the credentials straight into the container log.
without_xtrace() {
    local -
    set +o xtrace
    "$@"
}

need_cmd() {
    command -v "$1" > /dev/null 2>&1 || {
        error "Missing required command: $1"
        exit 2
    }
}

need_cmd mysqld
need_cmd mysql
need_cmd mysqladmin
need_cmd pmm-agent
need_cmd pmm-admin
need_cmd install
need_cmd python3
# Coreutils, as install already is, so this cannot fail in an image the
# entrypoint can otherwise run. Declared anyway so a missing stat can never
# silently take the cgroups gate's permissive branch on a host where clone3 is
# load-bearing, which is the one direction that guard exists to prevent.
need_cmd stat

usage() {
    cat << 'EOF'
mysql-entrypoint.sh

Container entrypoint for the sep-mysql service. Takes no arguments; every
input arrives as an environment variable.

Options:
  -h, --help    Show this help

Environment (required, generated by ./bootstrap.sh):
  SEP_MYSQL_ROOT_PASSWORD    root@localhost password
  SEP_MYSQL_BACKUP_PASSWORD  sep_backup@% password — the credential both backup
                             payloads authenticate with, via /root/.my.cnf
  SEP_MYSQL_PMM_PASSWORD     pmm@127.0.0.1 password, used by the PMM exporters

Environment (optional):
  PMM_AGENT_CONFIG_FILE      pmm-agent config path (default:
                             /usr/local/percona/pmm/config/pmm-agent.yaml)
  DEBUG=1                    Trace execution
EOF
    exit "${1:-0}"
}

[[ $# -eq 0 ]] || case "$1" in
    -h | --help) usage 0 ;;
    *)
        error "Unexpected argument: $1"
        usage 2
        ;;
esac

DATADIR=/var/lib/mysql
DEFAULTS_FILE=/root/.my.cnf
SEED_DIR=/opt/test_db
SOCKET=/var/lib/mysql/mysql.sock
# Lives on the data volume beside what it describes, and is written only after
# a complete import — the datadir existing says the import *started*
SEED_MARKER=/var/lib/mysql/.sep-seed-imported
# Same reasoning, and on the same volume as the accounts it records
USERS_MARKER=/var/lib/mysql/.sep-users-created
SERVICE_NAME=sep-mysql
PMM_CONFIG_FILE="${PMM_AGENT_CONFIG_FILE:-/usr/local/percona/pmm/config/pmm-agent.yaml}"
CGROUP_ROOT=/sys/fs/cgroup
# What Nomad's detect() requires before it will place a task into a cgroup
REQUIRED_CG2_CONTROLLERS=(cpuset cpu io memory pids)

# Wrapped rather than expanded at top level: ${VAR:?} puts the value itself
# into the xtrace line
require_secrets() {
    : "${SEP_MYSQL_ROOT_PASSWORD:?run ./bootstrap.sh first}" \
        "${SEP_MYSQL_BACKUP_PASSWORD:?run ./bootstrap.sh first}" \
        "${SEP_MYSQL_PMM_PASSWORD:?run ./bootstrap.sh first}"
}

without_xtrace require_secrets

# The controllers line is matched padded, and each controller with its own
# surrounding spaces, so cpu cannot match inside cpuset — a bare substring test
# would call that layout complete and refuse a node Nomad would have downgraded.
cg2_controllers_complete() {
    local available controller
    available=" $(cat "${CGROUP_ROOT}/cgroup.controllers" 2> /dev/null) "
    for controller in "${REQUIRED_CG2_CONTROLLERS[@]}"; do
        [[ ${available} == *" ${controller} "* ]] || return 1
    done
    return 0
}

# raw_exec spawns a task with clone3 only to place it into a cgroup, which is
# the unified hierarchy's CLONE_INTO_CGROUP path; Go issues the older clone
# otherwise. So an unimplemented clone3 costs this node nothing unless Nomad
# would really place it — which is what the two checks below establish, the
# same pair Nomad's own detect() makes (client/lib/cgroupslib/mount.go). Where
# it is load-bearing the node registers, fingerprints healthy, and fails every
# dispatch with `fork/exec …: function not implemented`; refuse to become that
# node. The two sources of ENOSYS and the fix for each are in README.md
# § Caveats, and the messages below name them.
require_clone3() {
    [[ ${SEP_FB_SKIP_CLONE3_CHECK:-0} == "1" ]] && return 0
    local out cgroup_fs
    out="$(python3 /usr/local/bin/clone3_probe.py 2>&1)" || true
    case "${out}" in
        *CLONE3_OK*) return 0 ;;
        *CLONE3_ENOSYS*)
            cgroup_fs="$(stat -fc %T "${CGROUP_ROOT}" 2> /dev/null)"
            if [[ ${cgroup_fs} != "cgroup2fs" ]]; then
                info "clone3 is unimplemented here (ENOSYS), but ${CGROUP_ROOT} is ${cgroup_fs:-unreadable}, not cgroup2fs: Nomad places no cgroup on this layout and spawns with plain clone; continuing"
                return 0
            fi
            if ! cg2_controllers_complete; then
                info "clone3 is unimplemented here (ENOSYS), but ${CGROUP_ROOT}/cgroup.controllers does not offer all of ${REQUIRED_CG2_CONTROLLERS[*]}: Nomad places no cgroup without them and spawns with plain clone; continuing"
                return 0
            fi
            error 'clone3 is unimplemented here (ENOSYS): Nomad cannot launch a single task on this node'
            error 'Unprivileged container? compose.yaml runs sep-mysql privileged; a plain docker run needs --privileged or --security-opt seccomp=unconfined'
            error 'Emulated amd64 on an arm64 engine? Set SEP_MYSQL_PLATFORM=linux/arm64 in .env and re-run ./bootstrap.sh to build this node natively, or enable Rosetta (Docker Desktop → Settings → General → "Apple Virtualization framework" + "Use Rosetta for x86_64/amd64 emulation")'
            error 'SEP_FB_SKIP_CLONE3_CHECK=1 starts the node anyway (MySQL and inventory work; task execution will not)'
            exit 3
            ;;
        *)
            info "clone3 probe gave no verdict (${out:-no output}); continuing"
            ;;
    esac
}

require_clone3

mysqld_pid=0

# Arguments: attempts, seconds between them, then the command and its arguments
# Returns: 0 as soon as the command succeeds, 1 once the attempts are spent
retry_cmd() {
    local attempts="$1" delay="$2"
    shift 2
    local attempt
    for ((attempt = 1; attempt <= attempts; attempt++)); do
        if "$@"; then
            return 0
        fi
        debug "attempt ${attempt}/${attempts} failed: $*"
        ((attempt < attempts)) && sleep "${delay}"
    done
    return 1
}

# mysqladmin's output separates the three states we care about: "mysqld is
# alive" once the server answers, "Access denied" once it answers but rejects
# these credentials — which still means it is up, and is all we are waiting for
# — and a socket error while it is still starting.
mysqld_is_answering() {
    local output
    output="$(mysqladmin --protocol=socket --user=root ping 2>&1)"
    [[ ${output} == *"mysqld is alive"* || ${output} == *"Access denied"* ]]
}

shutdown_mysqld() {
    info 'Stopping mysqld'
    kill -TERM "${mysqld_pid}" 2> /dev/null || true
    wait "${mysqld_pid}" 2> /dev/null || true
}

# Connect as root over the socket, ignoring every option file. --no-defaults is
# load-bearing rather than tidiness: option files outrank MYSQL_PWD, so a
# /root/.my.cnf left by an earlier boot would silently supply the service user's
# password for these root connections and they would fail to authenticate. It
# also drops /etc/my.cnf, hence the explicit socket.
mysql_as_root() {
    MYSQL_PWD="$1" mysql --no-defaults --protocol=socket --socket="${SOCKET}" \
        --user=root "${@:2}"
}

# A fresh datadir leaves root passwordless, and bootstrap_users below is what
# changes that. Report which of the two credentials the server accepts now, so
# an interrupted bootstrap can be re-entered from either state. The password
# travels as MYSQL_PWD rather than --password so it stays out of ps.
root_needs_password() {
    mysql_as_root '' --execute='SELECT 1' > /dev/null 2>&1 && return 1
    return 0
}

# The anonymous-user delete is what keeps sep_backup's '%' host matching a
# socket connection.
# Every statement is convergent rather than first-run-only, because this may be
# a re-entry after an interrupted bootstrap: CREATE ... IF NOT EXISTS pairs with
# an ALTER so a half-created account ends up carrying the password we expect
# instead of aborting the batch. Root's own password is set last on purpose —
# until it lands, a re-entry can still connect as passwordless root.
bootstrap_users() {
    local password=''
    root_needs_password && password="${SEP_MYSQL_ROOT_PASSWORD}"
    mysql_as_root "${password}" << SQL
DELETE FROM mysql.user WHERE User='';
DROP DATABASE IF EXISTS test;
CREATE USER IF NOT EXISTS 'sep_backup'@'%' IDENTIFIED WITH caching_sha2_password BY '${SEP_MYSQL_BACKUP_PASSWORD}';
ALTER USER 'sep_backup'@'%' IDENTIFIED WITH caching_sha2_password BY '${SEP_MYSQL_BACKUP_PASSWORD}';
GRANT ALL ON *.* TO 'sep_backup'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'pmm'@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY '${SEP_MYSQL_PMM_PASSWORD}';
ALTER USER 'pmm'@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY '${SEP_MYSQL_PMM_PASSWORD}'
    WITH MAX_USER_CONNECTIONS 10;
GRANT SELECT, RELOAD, PROCESS, REPLICATION CLIENT ON *.* TO 'pmm'@'127.0.0.1';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '${SEP_MYSQL_ROOT_PASSWORD}';
SQL
}

# /root is an image layer rather than the data volume, so this is rewritten on
# every boot. Consumers read different groups: [client] for PyMySQL and
# mydumper, [xtrabackup] and [mysqld] for xtrabackup. [client] deliberately
# carries no socket — PyMySQL would prefer it over the host it was given and
# send the Mydumper path to loopback instead of the node.
write_defaults_file() {
    install -m 0600 /dev/null "${DEFAULTS_FILE}" || return 1
    cat > "${DEFAULTS_FILE}" << EOF || return 1
[client]
user=sep_backup
password=${SEP_MYSQL_BACKUP_PASSWORD}

[mysqld]
datadir=${DATADIR}
socket=${SOCKET}

[xtrabackup]
user=sep_backup
password=${SEP_MYSQL_BACKUP_PASSWORD}
socket=${SOCKET}
EOF
}

# employees.sql sources its dump files by relative path, so importing it from
# anywhere else loads the schema, skips the data, and still exits 0. It opens
# with DROP DATABASE IF EXISTS, so re-importing repairs a partial load.
import_seed() {
    (cd "${SEED_DIR}" && mysql < employees.sql)
}

# The PMM Client image ships an empty pmm-agent.yaml, so the file existing says
# nothing about whether this node was ever set up. What does is the agent id
# pmm-agent writes into it — and preserving that id across recreates is the
# point: SEP matches inventory nodes by external id and never updates an
# existing one, so a re-registered node orphans catalogued backup rows.
agent_is_registered() {
    grep -qE '^id: *[^"[:space:]]' "${PMM_CONFIG_FILE}" 2> /dev/null
}

# A function rather than an inline call so without_xtrace can wrap it: the
# password would otherwise be expanded into the trace in the caller's frame,
# before the wrapper could suspend it
add_mysql_service() {
    pmm-admin add mysql \
        --username=pmm --password="${SEP_MYSQL_PMM_PASSWORD}" \
        --host=127.0.0.1 --port=3306 --query-source=perfschema \
        --service-name="${SERVICE_NAME}"
}

register_with_pmm() {
    if agent_is_registered; then
        info 'Node already registered; keeping the existing pmm-agent config'
    else
        # pmm-server reports healthy before pmm-managed will accept a
        # registration, so this is a bounded retry rather than a single attempt
        info 'Registering this node with pmm-server'
        retry_cmd 30 2 pmm-agent setup || {
            error 'pmm-agent setup failed'
            exit 1
        }
        success 'Node registered'
    fi

    # Restarting on exit keeps the supervised Nomad client alive across an agent
    # crash; without it the node silently drops out of SEP's executor-host list
    while true; do
        pmm-agent run --config-file="${PMM_CONFIG_FILE}"
        info 'pmm-agent exited; restarting it in 5s'
        sleep 5
    done &

    # `pmm-admin status` only reaches the agent's local API, which the loop
    # above opens almost immediately — well before the agent finishes
    # establishing its two-way channel to PMM Server. On first boot that gap
    # is invisible because `pmm-agent setup` above already blocked on a
    # server round-trip; a recreate skips setup (the config volume preserved
    # the agent id) and lands here with no such wait behind it. `pmm-admin
    # list`, which the already-registered check below needs anyway, cannot
    # succeed until the server connection is up, so gate on that instead.
    # Sized at ~2x the slowest observed pmm-server cold start (~90s), since
    # this gate needs pmm-managed to accept the agent's channel, which lands
    # after the server itself reports ready.
    retry_cmd 90 2 pmm-admin list > /dev/null || {
        error 'pmm-agent never connected to PMM Server'
        exit 1
    }

    # Established by asking rather than by swallowing a non-zero exit: a blanket
    # "already registered" fallback would also report success for a bad flag, an
    # agent race or an unreachable PMM, and that surfaces much later as a
    # service missing from SEP's backup-source picker
    if pmm-admin list 2> /dev/null | grep -qw "${SERVICE_NAME}"; then
        info "MySQL service ${SERVICE_NAME} is already registered"
    else
        without_xtrace add_mysql_service || {
            error 'pmm-admin add mysql failed'
            exit 1
        }
        success "Registered MySQL service ${SERVICE_NAME}"
    fi
}

main() {
    local first_boot=0
    [[ -d ${DATADIR}/mysql ]] || first_boot=1

    if ((first_boot)); then
        info 'Initialising the MySQL datadir'
        mysqld --initialize-insecure --user=mysql --datadir="${DATADIR}" || {
            error 'Could not initialise the datadir'
            exit 1
        }
        # A datadir this fresh cannot match a credential file left behind by an
        # earlier boot, and the stale one would outrank the command-line user
        rm -f "${DEFAULTS_FILE}"
    fi

    mysqld --user=mysql --datadir="${DATADIR}" &
    mysqld_pid=$!
    trap shutdown_mysqld INT TERM

    retry_cmd 120 1 mysqld_is_answering || {
        error 'mysqld never started answering on its socket'
        exit 1
    }
    success 'mysqld is up'

    # Marker-gated for the same reason as the seed below: a container stopped
    # between initialising the datadir and creating these accounts leaves a
    # datadir that reads as initialised, and a first_boot-gated step would then
    # be skipped for good — leaving a credentials file naming users that do not
    # exist. bootstrap_users is re-runnable, so the recovery is just to run it.
    if [[ ! -f ${USERS_MARKER} ]]; then
        without_xtrace bootstrap_users || {
            error 'Could not create the MySQL users'
            exit 1
        }
        : > "${USERS_MARKER}" || {
            error "Could not record the user bootstrap at ${USERS_MARKER}"
            exit 1
        }
        success 'Created the sep_backup and pmm users'
    fi

    # Nothing downstream reads this file, so an unnoticed failure here would
    # leave the node registering and looking selectable while every dispatched
    # backup fails to authenticate
    without_xtrace write_defaults_file || {
        error "Could not write ${DEFAULTS_FILE}"
        exit 1
    }
    success "Wrote ${DEFAULTS_FILE}"

    # Gated on the marker rather than on first_boot: the import runs for
    # minutes, and a container stopped partway leaves a datadir that looks
    # initialised. Keying off first_boot would then skip the import and leave a
    # half-seeded node that registers and passes every check upstream of a
    # backup actually reading the data.
    if [[ ! -f ${SEED_MARKER} ]]; then
        info 'Importing the employees seed dataset (this takes a few minutes)'
        import_seed || {
            error 'Could not import the employees seed dataset'
            exit 1
        }
        : > "${SEED_MARKER}" || {
            error "Could not record the seed import at ${SEED_MARKER}"
            exit 1
        }
        success 'Imported the employees seed dataset'
    fi

    register_with_pmm

    wait "${mysqld_pid}"
}

main "$@"
